# -*- coding: utf-8 -*-
"""ders13-hf_google_trends.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CYyrRFhdcSCPjb4Q-STluktt98V5jQNl
"""

#pip install pytrends

from pytrends.request import TrendReq
import matplotlib.pyplot as plt
import gradio as gr
def get_trends_plot(keywords_input, timeframe_option):
    trend = TrendReq()

    # Process keywords
    keywords = [k.strip() for k in keywords_input.split(',') if k.strip()]
    if not keywords:
        # Return an empty plot or an error message if no keywords are provided
        fig, ax = plt.subplots(figsize=(10, 6))
        ax.set_title('No Keywords Provided')
        plt.close(fig)
        return fig

    # Build payload and get data
    try:
        trend.build_payload(keywords, timeframe=timeframe_option)
        df = trend.interest_over_time()
    except Exception as e:
        fig, ax = plt.subplots(figsize=(10, 6))
        ax.text(0.5, 0.5, f"Error fetching data: {e}", horizontalalignment='center', verticalalignment='center', transform=ax.transAxes, color='red')
        ax.set_title('Error')
        plt.close(fig)
        return fig

    # Safely remove 'isPartial' column if it exists
    if 'isPartial' in df.columns:
        del df['isPartial']

    # Plotting
    fig, ax = plt.subplots(figsize=(10, 6))
    df.plot(ax=ax)
    ax.set_title(f'Google Trends for {", ".join(keywords)} (Timeframe: {timeframe_option})')
    ax.set_ylabel('Trend Score')
    ax.set_xlabel('Date')
    ax.grid(True)
    plt.close(fig) # Prevent matplotlib from displaying the figure directly
    return fig

timeframe_options = [
    'today 1-m', 'today 3-m', 'today 1-y', 'today 5-y',
    '2004-01-01 2024-03-29' # Example of a custom range format
]

iface = gr.Interface(
    fn=get_trends_plot,
    inputs=[
        gr.Textbox(label="Keywords (comma-separated)", placeholder="e.g., gemini, chat gpt, claude"),
        gr.Dropdown(timeframe_options, label="Timeframe", value='today 5-y')
    ],
    outputs=gr.Plot(label="Trend Over Time"),
    title="Google Trends Explorer",
    description="Explore Google search interest for multiple keywords over different timeframes."
)

iface.launch()